<a href="https://colab.research.google.com/github/ashwinimandlay/PyTorch_youtube/blob/main/2_Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_torch = torch.arange(10)
my_torch

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# reshape and view
my_torch = my_torch.reshape(2,5)
my_torch

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
# note that the number should add up 2*5 = 10 and we have 10 items
# reshape(3,5) will give an error as the numbers don't add up

In [5]:
# reshape if we don't know the number of items using -1
my_torch2 = torch.arange(10)
my_torch2

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
my_torch2 = my_torch2.reshape(2,-1)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [9]:
# note that the -1 represents 2*(something) = 10
# this 'something' should be an integer value or an error will come up

In [10]:
my_torch2 = my_torch2.reshape(-1,5)
my_torch2

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [11]:
my_torch3 = torch.arange(10)
my_torch3

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# .view() is same as .reshape()

In [13]:
my_torch4 = my_torch3.view(2,5)
my_torch4

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [15]:
# with reshape and view, they will update
my_torch5 = torch.arange(10)
my_torch5

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
my_torch6=my_torch5.reshape(2,5)
my_torch6

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [17]:
my_torch5[0] = 100
my_torch5

tensor([100,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [18]:
my_torch6

tensor([[100,   1,   2,   3,   4],
        [  5,   6,   7,   8,   9]])

In [19]:
# slices
my_torch7 = torch.arange(10)
my_torch7

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
# grab a item
my_torch7[7]

tensor(7)

In [21]:
# notice that it is not a number but a tensor

In [23]:
my_torch8 = my_torch7.reshape(5,2)
my_torch8

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
my_torch8[:,1]

tensor([1, 3, 5, 7, 9])

In [25]:
# return a column
my_torch8[:,1:]

tensor([[1],
        [3],
        [5],
        [7],
        [9]])