<a href="https://colab.research.google.com/github/ashwinimandlay/PyTorch_youtube/blob/main/pytorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensors

In [2]:
import torch
import numpy as np

In [4]:
my_list = [[1,2,3,4,4],[1,2,3,4,5]]
print(my_list)

[[1, 2, 3, 4, 4], [1, 2, 3, 4, 5]]


In [5]:
np1 = np.random.rand(3,4)

In [7]:
np1

array([[0.26310651, 0.72396427, 0.67807489, 0.97517629],
       [0.93188736, 0.08738994, 0.31212429, 0.23342298],
       [0.27909648, 0.72988339, 0.48584712, 0.12972492]])

In [8]:
np1.dtype

dtype('float64')

In [9]:
tensor_2d = torch.randn(3,4)
tensor_2d

tensor([[-1.6436,  1.3217,  0.6171, -0.2155],
        [ 0.2948,  1.1702,  1.2360,  0.6195],
        [-0.4935,  1.1107,  1.2632,  0.0654]])

In [10]:
tensor_2d.dtype

torch.float32

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.2631, 0.7240, 0.6781, 0.9752],
        [0.9319, 0.0874, 0.3121, 0.2334],
        [0.2791, 0.7299, 0.4858, 0.1297]], dtype=torch.float64)

In [13]:
# by default the tensor is float32